version: '3.4'

services:
  db:
    image: pacceconnect-db
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: pacceconnect-db
    ports:
      - "3308:3306"
    networks:
      - pacceconnect-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    hostname: rabbitmq
    restart: always
    environment:
      TZ: America/Sao_Paulo
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: passw123
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - pacceconnect-network
  web-api:
    image: ${DOCKER_REGISTRY-}web-api
    container_name: web-api
    restart: always
    build:
      context: .
      dockerfile: Service/Consumers/WebAPI/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - db
      - rabbitmq
    networks:
      - pacceconnect-network
networks:
  pacceconnect-network:
    driver: bridge
